name: Simple Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aws
    steps:
    - name: Prepare Environment
      uses: appleboy/ssh-action@v0.1.10
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: >- 
          sudo apt install curl && 
          curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash  && 
          exit
    - name: Launch bot
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: >-
          cd discord-js-bot/ && 
          source ~/.bashrc &&
          nvm install 18.14.2 &&
          sudo npm install -g pm2 && 
          pm2 stop Tsureimu && 
          git pull origin master &&
          npm install &&
          pm2 start Tsureimu && 
          exit
