name: Simple Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aws
    steps:
    - name: Launch bot
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: >-
          cd discord-js-bot/ && 
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - &&
          sudo apt-get -o Dpkg::Options::="--force-overwrite" install -y nodejs &&
          node -v &&
          sudo npm install -g pm2 && 
          # pm2 stop all &&
          git pull origin master &&
          npm install &&
          npm ci &&
          pm2 start src/index.js --name Tsureimu
